image:
  repository: my-backend-new
  tag: latest
  pullPolicy: Never

namespace: "default"
replicaCount: 1

service:
  type: NodePort
  port: 80
  targetPort: 3001
  nodePort: 30001

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80