image:
  repository: my-backend-prod
  tag: latest
  pullPolicy: Never

namespace: "default"
replicaCount: 2

service:
  type: NodePort
  port: 80
  targetPort: 3001
  nodePort: 30001

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80