image:
  repository: my-backend-2
  tag: latest
  pullPolicy: Never  # Don't pull from an external registry

namespace: "default"
replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 3001
  nodePort: 30001
